#! /bin/bash
sudo docker rm maudbox 2&> /dev/null
# for an interactive shell.  copy artifacts or goodies out to ~/attic to preserve
sudo docker run -it --name maudbox -v "$(pwd)"/attic:/home/kewluser/attic maud:latest /bin/bash
