#! /bin/bash
sudo docker rm maudbox 2&> /dev/null
# for an interactive shell.  copy artifacts out to ~/outhack to preserve
sudo docker run -it --name maudbox -v "$(pwd)"/outhack:/home/kewluser/outhack maud:latest /bin/bash
