#! /bin/bash
sudo docker rm maudbox 2&> /dev/null
sudo docker run -it --name maudbox -v "$(pwd)"/saves:/home/kewluser/nh/install/games/lib/nethackdir/save maud:latest /home/kewluser/nh/install/games/nethack
